DIRS=\
TRNC\
USR\
PRM\
ROL\
HASH\
MATCH\
POP\
PASS\
SDB\
INFO\
ENV\
ENVC\
GUID\
CFG\
SFI\
PRO\
DIR\
SCK\
UNIT\
CMD\
FIL\
COL\
TXT\
ICONV\
REX\
PCRE\
GIT\
GITU\
INI\
HTOOL\
GSV\
ICOL\

include ../make/makefile.core
include ../OpenSSL/makefile.openssl
