DIRS=\
UNIT\
DBIM\
DB\
DBSQL\
SQL\
SQLTE\
EDI\
CFG\
DIR\
SCK\
PRO\
CMD\
FIL\
COL\
EXP\
SFI\
CXML\
EVP\
REG\
PASS\
GUID\
PRM\
ROL\
HASH\
INI\
POP\

include ../make/makefile.core
include ../OpenSSL/makefile.openssl
