DIRS=\
SDBT\
SDBU\
SDB\
SFI\
INFO\
ENV\
ENVC\
DIR\
UNIT\
FIL\
SCK\
PRO\
CMD\
COL\
HASH\
MATCH\
TXT\
REX\
PCRE\
ICONV\
GIT\
GITU\
INI\
POP\
GSV\
HTOOL\
CFG\
PASS\
PRM\
ROL\
GUID\

include ../make/makefile.core
include ../OpenSSL/makefile.openssl
