DIRS=\
HELP\
WEBI\
PACK\
CACHE\
PRO\
DIR\
CFG\
SCK\
UNIT\
CMD\
FIL\
COL\
SFI\
GUID\
GZIP\
PASS\
PRM\
ROL\
HASH\
INI\
POP\

include ../make/makefile.core
include ../OpenSSL/makefile.openssl
include ../zlib/makefile.zlib
