DIRS=\
CMD\
FIL\
DIR\
DBDVER\
PRO\
WEB\
SCKS\
GUID\
SFI\
SCK\
SCKB\
GZIP\
PACK\
WEBI\
CACHE\
DBG\
COL\

include ../make/makefile.core
include ../openssl/makefile.openssl
include ../zlib/makefile.zlib
