//---------------------------------------------------------------------------
// Copyright (C) 1997-2008 iNTERFACEWARE Inc.  All Rights Reserved
//
// Module: COLmath
//
// Description:
//
// Implementation
//
// Author: Eliot Muir
// Date:   Fri 01/16/2004
//---------------------------------------------------------------------------
#include "COLmath.h"
#include <COL/COLstring.h>
#include "COLlog.h"
COL_LOG_MODULE;

#include <time.h>
#include <ctype.h>

#ifndef _WIN32
#include <wchar.h>
#endif

void COLmath::resetRandomGenerator(){
#ifdef _WIN32
   // we use rand_s() on Windows, which does not use the seed generated by the srand function
#else
   // we use the machine type call
   srand((unsigned int)time(NULL));
#endif
}


COLuint32 COLmath::randomNumber(COLuint32 Max)
{
#ifdef _WIN32
   // rand_s returns a random integer in the range 0 to UINT_MAX
   unsigned int Number;
   errno_t Error = rand_s(&Number);
   COLPOSTCONDITION(Error == 0);
   return  Number % Max;
#else
   COLPRECONDITION(Max <= RAND_MAX);
   return rand() % Max;
#endif
}

// It's okay to have this here.
char COLmath::toUpper(char Character){ // Cannot error check since there is no return code for an error
   return toupper(Character);
}

COLint64 COLmath::atoi64(const char* pNumberString){
#ifdef _WIN32
   return _atoi64( pNumberString );
#else
   return atoll( pNumberString );
#endif
}

COLuint16 COLmath::atous(const char* pNumberString) {
   COL_FUNCTION(COLmath::atous);
   COLstring NumberString(pNumberString);
   COL_VAR(NumberString);
   NumberString = NumberString.strip(COLstring::Leading, ' ');
   if (NumberString.size() < 1) {
      return 0;
   }
   if (NumberString[0] == '-') {
      return 0;
   }
   unsigned int BigEnough = ::atoi(NumberString.c_str());
   if (BigEnough > COL_UINT_16_MAX) {
      return 0;
   }
   COL_VAR(BigEnough);
   return (COLuint16)BigEnough;
}

COLuint64 COLmath::parseUint64(const char* pNumberString, COLuint32 CountOfDigit){
   COLint8 AsciiCode0 = 48;
   COLint8 AsciiCode9 = 57;
   COLuint64 NewValue = 0;
   // If the number has greater than 20 digits, then it is too large.
   // If the number is 20 digits and starts with a digit > 1, then it is too large.
   if (CountOfDigit > 20 || (CountOfDigit == 20 && (COLuint8)pNumberString[0] > AsciiCode0+1 && (COLuint8)pNumberString[0] <= AsciiCode9)){
      return COL_UINT_64_MAX;
   }

   // convert the string into a number
   for (COLuint32 DigitIndex = 0; DigitIndex < CountOfDigit; DigitIndex++){
      COLint8 CurrentChar = (COLint8)pNumberString[DigitIndex];

      // Check if the current character is invalid
      if (CurrentChar < AsciiCode0 || CurrentChar > AsciiCode9){
         return 0;
      }

      COLuint64 CurrentDigit = CurrentChar - AsciiCode0;
      COLuint64 PowerBase = power(10, CountOfDigit - DigitIndex - 1);
      COLuint64 CurrentDigitValue = CurrentDigit*PowerBase;

      // If adding CurrentDigitValue to NewValue would cause an integer
      // overflow, then just return COL_UINT_64_MAX.
      if (COL_UINT_64_MAX - NewValue < CurrentDigitValue){
         return COL_UINT_64_MAX;
      }

      NewValue += CurrentDigitValue;
   }

   return NewValue;
}

COLint64 COLmath::power(const COLint64 Base, const COLint64 Exponent){
   COLPRECONDITION(Exponent >= 0);
   COLint64 Result = 1;
   for (COLuint32 Power = 0; Power < Exponent; Power++){
      Result *= Base;
   }
   return Result;
}

void COLmath::incMultiBytePointer(COLuint8*& pPointer){
#ifdef _WIN32
   // TODO - it would be interesting to profile relative
   // performance on these functions in Windows.
   pPointer = _mbsinc(pPointer);
#else
   int Increment = mblen((const char*)pPointer, MB_CUR_MAX);
   if (Increment == -1){
      COL_ERROR_STREAM("Invalid multibyte sequence", COLerror::PreCondition);
   }
   if (Increment == 0){
      Increment = 1;
   }
   pPointer = pPointer + Increment;
#endif
}

COLuint32 COLmath::multiByteLength(COLuint8*& pPointer){
   int Length = mblen((const char*) pPointer, MB_CUR_MAX);
   if (Length == -1) {
      COL_ERROR_STREAM("Invalid multibyte sequence", COLerror::PreCondition);
   }
   if (Length == 0) {
      Length = 1;
   }
   return Length;
}

static bool COLmathIsInteger(const char* pInteger){
   int ConvertInt = ::atoi(pInteger);
   COLstring ConvertedInteger = COLintToString(ConvertInt);
   COL_VAR3(pInteger, ConvertInt, ConvertedInteger);
   return !ConvertedInteger.compare(pInteger);
}

bool COLmath::isInteger(const COLstring& Integer){
   return COLmathIsInteger(Integer.c_str());
}

bool COLmath::isInteger(const char* pInteger){
   return COLmathIsInteger(pInteger);
}
