BINARY=service_demo

IFW_MAKE_STRIP_BINARY = 1

SRC=\
SDMexampleServer.cpp\
SDMmain.cpp\

MODULES=\
SDM\
PRO\
PAR\
PRO\
FMT\
SCK\
REG\
FIL\
CMD\
COL\

LDEXTRA += $(IFW_UNITTEST_LDEXTRA)

include ../makefiles/binary.makefile
