TARGET=webpacker

DIRS=\
PACK\
UNIT\
SCK\
PRO\
SFI\
FIL\
CMD\
COL\
DIR\
GZIP\
WEBI\
CACHE\

include ../make/makefile.core
include ../OpenSSL/makefile.openssl
include ../zlib/makefile.zlib
include ../xmlsec/makefile.xmlsec