#ifndef __TRN_TRAVERSER_H__
#define __TRN_TRAVERSER_H__
//---------------------------------------------------------------------------
// Copyright (C) 1997-2013 iNTERFACEWARE Inc.  All Rights Reserved
//
// Module: TRNtraverser
//
// Description:
//
// TRNtraverser class.
//
// Author: Kevin Senn
// Date:   Tuesday, April 26th, 2011 @ 01:08:07 PM
//
//---------------------------------------------------------------------------
#include <COL/COLlist.h>
#include <COL/COLminimumInclude.h>

#include <LUA/LUAheader.h>

class REXmatcher;
class NODplace;
class NODaddress;
class TRNintellisenseOption;
class TRNtreeFormatter;

extern const COLstring TRN_ROOT_KEY;
extern const COLstring TRN_NODE_TRAVERSER_TYPE;
extern const COLstring TRN_LUA_TRAVERSER_TYPE;

extern const COLstring TRN_STRING_KEY_PREFIX;
extern const COLstring TRN_NUMBER_KEY_PREFIX;
extern const COLstring TRN_BOOL_KEY_PREFIX;

class TRNtraverser 
{
public:
   TRNtraverser();
   virtual ~TRNtraverser();

   // Returns type info for the current item.
   virtual void getTypeInfo(int& ProtocolType, int& NodeType) const = 0;

   // A key that will uniquely identify the current item.
   virtual void getUniqueKey(COLstring& Key) const = 0;

   // Sets the Lua key for the current item (iff a Lua table is being traversed).
   virtual void getLuaKey(COLstring& LuaKey) const = 0;

   // Returns true if the item being traversed is a "complex Lua item"
   // (a table or userdata), and therefore all 'treeview labels' are
   // not guaranteed reproducible from the sum of its parts
   // (they could be generated by metamethods).
   virtual bool isComplexLuaItem() const = 0;

   ///////////////////////////////////////
   // Begin traversal-related functions //
   ///////////////////////////////////////

   // Step to the next item.
   // Before this is called, the current item is the root, rather than one of the children.
   // Returns false if there is no next item.
   virtual bool stepNext() = 0;

   // Is the current item a leaf?
   virtual bool isLeaf() const = 0;

   // Is the current item null?
   virtual bool isNull() const = 0;

   //Returns NODE if TRNtraverserNode, returns LUA for TRNtraverserLua
   virtual const COLstring traverserType() const = 0;

   // Return a traverser for this item's children.
   // Calling code should take ownership of the traverser.
   // Should only be called after stepping to a child node, and if isLeaf() is true.
   virtual TRNtraverser* traverser() const = 0;

   ///////////////////////////////////////
   // Auto-completion-related functions //
   ///////////////////////////////////////

   // The auto-completion-related functions should only be called after stepNext() has been
   // called for the first time.

   // INDEX_MATCH is the strongest match.  An index match may also be a string match.
   enum eSearchResult{
      NO_MATCH=0,
      STRING_MATCH=1,
      INDEX_MATCH=2
   };

   // Returns true if the option is lower priority.  For example, null NOD nodes have
   // a lower priority, as do metamethod entries in Lua tables.
   virtual bool isLowPriority() const = 0;

   // Returns an eSearchResult, given the search criteria.
   // Should only be called after stepping to a child node.
   virtual eSearchResult findMatch(const REXmatcher& SearchRegex, int SearchIndex) const = 0;

   // Returns the text to display for an intellisense option for the current item.
   // Should only be called after stepping to a child node.
   // Will truncate long strings if necessary.
   virtual COLstring optionDisplayText(COLstring* pFuncName=NULL) const = 0;

   // Returns the text to display for an intellisense option for the current item (when doing a deep search).
   // SearchRegex will be used to highlight parts of the name/value.
   // RootDisplayText is the text which will be prepended to the current item's display text.
   // IsIndexMatch indicates whether or not the item matchs an index entered by the user.
   // Should only be called after stepping to a child node.
   // Will truncate long strings if necessary.
   virtual COLstring deepOptionDisplayText(const REXmatcher& SearchRegex, const COLstring& RootDisplayText, bool IsIndexMatch) const = 0;

   // Returns the Lua expression to "auto-complete" for an intellisense option for the current item.
   // RootVar is the beginning of the expression.
   // Should only be called after stepping to a child node.
   virtual COLstring optionFullText(const COLstring& RootVar) const = 0;

   //Returns the value of m_pChild for TRNtraverserNode
   //Used in the generation of a single text option when more than 1 text nodes are 
   //found in an XML node.
   //Ticket #27741 for more information
   virtual COLstring childValue() const = 0;
    
   // Very similar to above function but is used check for collisions with built in node methods.
   // This signature is currently only used in TRNaddChildOptions.
   // For more information check out ticket #27741 and branch t27741.
   virtual COLstring optionFullText(const COLstring& RootVar, lua_State* L) const = 0;
   // Serializes the current item, for display purposes, and writes it to Sink.
   // If pSearchRegex is defined, it will be used to highlight search matches in the text.
   // Will truncate the tree value if it is too long.
   virtual void writeTreeValue(COLstring& String, COLstring* pFuncName=NULL, const REXmatcher* pSearchRegex = NULL) const = 0;

   ////////////////////////////////
   // Treeview-related functions //
   ////////////////////////////////

   // ShortLabel will be set to text to show for the current node when it is expanded (usually just the name/index).
   // LongLabel will be set to text to show for the current node when it is collapsed (usually the entire serialized object).
   virtual void getTreeviewText(COLstring& ShortLabel, COLstring& LongLabel) const = 0;

   // The following functions are for traversing Lua trees only.
   virtual void getTreeviewKey(COLstring& Key) const = 0;
   virtual void getTreeviewValue(COLstring& Value) const = 0; // valid iff isLeaf() is true.
   virtual const NODplace* nodPlace() const = 0;

private:
   TRNtraverser(const TRNtraverser& Orig); // not allowed
   TRNtraverser& operator=(const TRNtraverser& Orig); // not allowed
};

// Create a traverser for a NOD tree.
// An example of when AllowDummyItems should be false is when providing
// auto-completion for a read-only tree.
TRNtraverser* TRNcreateTraverser(const NODplace& RootPlace);
TRNtraverser* TRNcreateTraverser(const NODaddress& RootAddress);

// Create a traverser for a Lua table or userdata.
// ItemIndex must be a real (positive) index (not a stack-top relative index).
// ForDisplay specifies whether we are traversing for display purposes.  If
// true, complex keys will not be skipped, and the _displayKeys metamethod will be
// used, if available, to get the keys.  If false, complex keys will be skipped,
// and the _keys metamethod will be used, if available, to get the keys.
// For auto-completion ForDisplay should be false, and for generating treeviews
// it should be true.
// IndexChar should be the character the user is using to index - '[', '.', or ':'.
// Can also be 0 for N/A.
// Beware that during the lifetime of this traverser, the stack may not be in the
// same state in which it started.  But once the iteration is finished, the stack
// should be back to its original state.
TRNtraverser* TRNcreateTraverser(lua_State* L, int ItemIndex, bool ForDisplay, char IndexChar);

COLstring TRNsearchMatchEscaper(const COLstring& UnescapedString);

COLstring TRNsearchResult(TRNtraverser::eSearchResult Result);

#endif // end of defensive include