TARGET = release_tool

DIRS=\
WEB\
USG\
USR\
HASH\
MATCH\
POP\
PRM\
CFG\
ROL\
PASS\
SDB\
INFO\
ENV\
ENVC\
DIR\
PACK\
CACHE\
GUID\
GZIP\
FIL\
HTTP\
SFI\
SCKB\
SCKS\
SCK\
PRO\
CMD\
UNIT\
COL\
WEBI\
TXT\
ICONV\
REX\
PCRE\
GIT\
GITU\
INI\
HTOOL\
GSV\
MZIP\
DRX\
RGN\
REG\

include ../make/makefile.core
include ../libcurl/makefile.libcurl
