DIRS=\
DRX\
RGN\
REG\
WEB\
COL\
UNIT\
CMD\
SFI\
SCK\
CACHE\
FIL\
USR\
DIR\
WEBI\
SCKB\
SCKS\
POP\
PRM\
GZIP\
CFG\
PASS\
ROL\
HASH\
PRO\
GUID\
USG\
PACK\
SDB\
MATCH\
INFO\
REX\
PCRE\
ENV\
ENVC\

include ../make/makefile.core
include ../libcurl/makefile.libcurl
