# TODO - GIT pulls in CFG, GUID


DIRS=\
GIT\
GITU\
GITE\
GITC\
GSV\
WEB\
USG\
CACHE\
GZIP\
WEBI\
SCKB\
SCKS\
USR\
SDB\
PACK\
MATCH\
INFO\
ENV\
ENVC\
TXT\
ICONV\
REX\
PCRE\
GUID\
POP\
SFI\
CFG\
DIR\
INI\
UNIT\
FIL\
SCK\
PRO\
CMD\
COL\
PASS\
ROL\
PRM\
HASH\
HTOOL\
DRX\
RGN\
REG\

include ../make/makefile.core
include ../libcurl/makefile.libcurl
