//---------------------------------------------------------------------------
// Copyright (C) 1997-2008 iNTERFACEWARE Inc.  All Rights Reserved
//
// Module: SFIuriEscapeFilter
//
// Description:
//
// Implementation.
//
// Author: Matt Lawrence, Andrew Vajoczki
// Date: August 9, 2006
//
//---------------------------------------------------------------------------
#include "SFIprecomp.h"
#pragma hdrstop

#include "SFIuriEscapeFilter.h"

#include <COL/COLsinkString.h>

SFIuriEscapeFilter::SFIuriEscapeFilter(COLsink* ipNext): COLfilter(ipNext){}

SFIuriEscapeFilter::~SFIuriEscapeFilter(){}

//
// This table is generated by defining GENERATE_SFI_URI_ESCAPE_LOOKUP_TABLE
//
static unsigned char s_DontEscapeLookupTable[256] =
{
   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
   0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,
   1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,
   0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
   1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,1,
   0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
   1,1,1,1,1,1,1,1,1,1,1,0,0,0,1,0,
   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
   0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
};

static unsigned char s_DontEscapeLookupTableGenerous[256] =
{
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
   0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
   0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
   1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
   0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};


COLuint32 SFIuriEscapeFilter::write(const void* pBuffer, COLuint32 SizeOfBuffer) {
   return write(pBuffer, SizeOfBuffer, true, false);
}

COLuint32 SFIuriEscapeFilter::write(const void* pBuffer, COLuint32 SizeOfBuffer, bool SpacesToPlusses, bool Generous) {
   COLsink& Output = next();
   unsigned char* pDontEscapeTable = Generous ? s_DontEscapeLookupTableGenerous : s_DontEscapeLookupTable;
   const unsigned char* Unescaped = (const unsigned char*)pBuffer;
   int UnescapedLength = SizeOfBuffer;
   for (int i = 0; i < UnescapedLength; ++i) {
      unsigned char c = Unescaped[i];
      unsigned char CharBuffer[4];
      int CharBufferLength = 1;
      if (pDontEscapeTable[(unsigned char)c]) {
         CharBuffer[0] = c;
      } else if (c == ' ' && SpacesToPlusses) {
         CharBuffer[0] = '+';
      } else {
         static const char hex[] = "0123456789ABCDEF";
         unsigned char u = (unsigned char)c;
         CharBuffer[0] = '%';
         CharBuffer[1] = hex[u >> 4];
         CharBuffer[2] = hex[u & 0xf];
         CharBufferLength = 3;
      }
      Output.write(CharBuffer, CharBufferLength);
   }
   return SizeOfBuffer;
}

//#define GENERATE_SFI_URI_ESCAPE_LOOKUP_TABLE
#ifdef GENERATE_SFI_URI_ESCAPE_LOOKUP_TABLE
int generateDontEscapeLookupTable()
{
   COLcout << "static unsigned char s_DontEscapeLookupTable[256] =\n{";
   for (unsigned i = 0; i < 256; ++i)
   {
      if (i % 16 == 0) COLcout << "\n   ";
      unsigned char c = (unsigned char)i;
      int DontEscape = ((c >= 'A' && c <= 'Z')
         || (c >= 'a' && c <= 'z')
         || (c >= '0' && c <= '9')
         || c == '-' || c == '.' || c == '_' || c == '~') ? 1 : 0;
      COLcout << DontEscape;
      if (i != 255) COLcout << ',';
   }
   COLcout << "\n};\n";
}
static int dummy = generateDontEscapeLookupTable();
#endif

COLstring SFIuriEscape(const COLstring& Input, bool SpacesToPlusses, bool Generous){
   COLstring Output;
   COLsinkString Sink(Output);
   SFIuriEscapeFilter Filter(&Sink);
   Filter.write(Input.c_str(), Input.size(), SpacesToPlusses, Generous);
   return Output;
}
