const HL7_2_1 =
          {"nodes":{
                "ACC":{
                   "desc":"Accident",
                   "type":"segment",
                   "children":[
                      {"type":"TS", "desc":"Accident date/time"},
                      {"type":"ID", "desc":"Accident code"     },
                      {"type":"ST", "desc":"Accident Location" }]},
                "ACK":{
                   "desc":"Acknowledgment",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"          ,"req":true},
                      {"type":"MSA", "desc":"Message Acknowledgement" ,"req":true},
                      {"type":"ERR", "desc":"Error"                  }]},
                "AD":{
                   "desc":"Address",
                   "type":"composite",
                   "children":[
                      {"type":"ST", "desc":"Street Address"    },
                      {"type":"ST", "desc":"Other designation" },
                      {"type":"ST", "desc":"City"              },
                      {"type":"ST", "desc":"State or province" },
                      {"type":"ST", "desc":"Zip or Postal Code"},
                      {"type":"ID", "desc":"Country "          }]},
                "ADD":{
                   "desc":"Addendum",
                   "type":"segment",
                   "children":[
                      {"type":"ST", "desc":"1"}]},
                "ADTA01":{
                   "desc":"Admit a patient",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"                 ,"req":true},
                      {"type":"EVN", "desc":"Event Type"                     ,"req":true},
                      {"type":"PID", "desc":"Patient Identification"         ,"req":true},
                      {"type":"NK1", "desc":"Next of Kin/Associated Parties" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"                  ,"req":true},
                      {"type":"DG1", "desc":"Diagnosis"                     }]},
                "ADTA02":{
                   "desc":"Transfer a patient",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true}]},
                "ADTA03":{
                   "desc":"Discharge a patient",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true}]},
                "ADTA04":{
                   "desc":"Register a patient",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"                 ,"req":true},
                      {"type":"EVN", "desc":"Event Type"                     ,"req":true},
                      {"type":"PID", "desc":"Patient Identification"         ,"req":true},
                      {"type":"NK1", "desc":"Next of Kin/Associated Parties" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"                  ,"req":true},
                      {"type":"DG1", "desc":"Diagnosis"                     }]},
                "ADTA05":{
                   "desc":"Preadmit a patient",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"                 ,"req":true},
                      {"type":"EVN", "desc":"Event Type"                     ,"req":true},
                      {"type":"PID", "desc":"Patient Identification"         ,"req":true},
                      {"type":"NK1", "desc":"Next of Kin/Associated Parties" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"                  ,"req":true},
                      {"type":"DG1", "desc":"Diagnosis"                     }]},
                "ADTA06":{
                   "desc":"Transfer an outpatient to inpatient",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true}]},
                "ADTA07":{
                   "desc":"Transfer an inpatient to outpatient",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true}]},
                "ADTA08":{
                   "desc":"Update patient information",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true},
                      {"type":"DG1", "desc":"Diagnosis"             }]},
                "ADTA09":{
                   "desc":"Patient departing",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true},
                      {"type":"DG1", "desc":"Diagnosis"             }]},
                "ADTA10":{
                   "desc":"Patient arriving",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true},
                      {"type":"DG1", "desc":"Diagnosis"             }]},
                "ADTA11":{
                   "desc":"Cancel admit",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true},
                      {"type":"DG1", "desc":"Diagnosis"             }]},
                "ADTA12":{
                   "desc":"Cancel transfer",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true},
                      {"type":"DG1", "desc":"Diagnosis"             }]},
                "ADTA13":{
                   "desc":"Cancel discharge",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true},
                      {"type":"DG1", "desc":"Diagnosis"             }]},
                "ADTA14":{
                   "desc":"Pending admit",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true},
                      {"type":"DG1", "desc":"Diagnosis"             }]},
                "ADTA15":{
                   "desc":"Pending transfer",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true},
                      {"type":"DG1", "desc":"Diagnosis"             }]},
                "ADTA16":{
                   "desc":"Pending discharge",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true},
                      {"type":"DG1", "desc":"Diagnosis"             }]},
                "ADTA17":{
                   "desc":"Swap patients",
                   "type":"message",
                   "children":[
                      {"type":"MSH",         "desc":"Message Header" ,"req":true},
                      {"type":"EVN",         "desc":"Event Type"     ,"req":true},
                      {"type":"GRP1_ADTA17", "desc":""               ,"req":true ,"repeats":true}]},
                "ADTA18":{
                   "desc":"Merge patient information (backwards compatibility only)",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"            ,"req":true},
                      {"type":"EVN", "desc":"Event Type"                ,"req":true},
                      {"type":"PID", "desc":"Patient Identification"    ,"req":true},
                      {"type":"MRG", "desc":"Merge Patient Information" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"            }]},
                "ADTA19":{
                   "desc":"No description.",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"                  ,"req":true},
                      {"type":"QRD", "desc":"Original Style Query Definition" ,"req":true}]},
                "ADTA20":{
                   "desc":"Nursing/Census application updates",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"    ,"req":true},
                      {"type":"EVN", "desc":"Event Type"        ,"req":true},
                      {"type":"NPU", "desc":"Bed Status Update" ,"req":true}]},
                "ADTA21":{
                   "desc":"Leave of absence - out (leaving)",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true}]},
                "ADTA22":{
                   "desc":"Leave of absence - in (returning)",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true}]},
                "ADTA23":{
                   "desc":"Delete a patient record",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true}]},
                "ADTA24":{
                   "desc":"Link patient information",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true}]},
                "BARP01":{
                   "desc":"Add and update patient account",
                   "type":"message",
                   "children":[
                      {"type":"MSH",         "desc":"Message Header"         ,"req":true},
                      {"type":"EVN",         "desc":"Event Type"             ,"req":true},
                      {"type":"PID",         "desc":"Patient Identification" ,"req":true},
                      {"type":"GRP1_BARP01", "desc":""                       ,"req":true ,"repeats":true}]},
                "BARP02":{
                   "desc":"Purge patient account",
                   "type":"message",
                   "children":[
                      {"type":"MSH",         "desc":"Message Header" ,"req":true},
                      {"type":"EVN",         "desc":"Event Type"     ,"req":true},
                      {"type":"GRP1_BARP02", "desc":""               ,"req":true ,"repeats":true}]},
                "BHS":{
                   "desc":"Batch Header",
                   "type":"segment",
                   "children":[
                      {"type":"ST", "desc":"Batch Field Separator"     ,"req":true},
                      {"type":"ST", "desc":"Batch Encoding Characters" ,"req":true},
                      {"type":"ST", "desc":"Batch Sending Application"},
                      {"type":"ST", "desc":"Batch Sending Facility"   },
                      {"type":"ST", "desc":"Batch Rcving Application" },
                      {"type":"ST", "desc":"Batch Receiving Facility" },
                      {"type":"TS", "desc":"Batch Creation Date/Time" },
                      {"type":"ST", "desc":"Batch Security"           },
                      {"type":"ST", "desc":"Batch Name/ID/Type"       },
                      {"type":"ST", "desc":"Batch Comment"            },
                      {"type":"ST", "desc":"Batch Control ID"         },
                      {"type":"ST", "desc":"Reference Batch Cntrl ID" }]},
                "BLG":{
                   "desc":"Billing",
                   "type":"segment",
                   "children":[
                      {"type":"CM", "desc":"When to Charge"        },
                      {"type":"CM", "desc":"Value Type"            },
                      {"type":"CM", "desc":"Observation Identifier"}]},
                "BTS":{
                   "desc":"Batch Trailer",
                   "type":"segment",
                   "children":[
                      {"type":"ST", "desc":"Batch Message Count"},
                      {"type":"ST", "desc":"Batch Comment"      },
                      {"type":"CM", "desc":"Batch Totals"       }]},
                "CE":{
                   "desc":"Coded element",
                   "type":"composite",
                   "children":[
                      {"type":"ST", "desc":"Identifier"           },
                      {"type":"ST", "desc":"Text"                 },
                      {"type":"ST", "desc":"Name of coding system"}]},
                "CK":{
                   "desc":"Composite ID with Check Digit",
                   "type":"composite",
                   "children":[
                      {"type":"NM", "desc":"ID Number"  },
                      {"type":"NM", "desc":"Check Digit"}]},
                "CM":{
                   "desc":"Composite",
                   "type":"composite",
                   "children":[
                      {"type":"ST", "desc":"Field1"},
                      {"type":"ST", "desc":"Field2"},
                      {"type":"ST", "desc":"Field3"},
                      {"type":"ST", "desc":"Field4"},
                      {"type":"ST", "desc":"Field5"},
                      {"type":"ST", "desc":"Field6"}]},
                "CN":{
                   "desc":"Composite ID Number and Name",
                   "type":"composite",
                   "children":[
                      {"type":"ST", "desc":"ID Number"     },
                      {"type":"ST", "desc":"Family Name"   },
                      {"type":"ST", "desc":"Given Name"    },
                      {"type":"ST", "desc":"Middle Initial"},
                      {"type":"ST", "desc":"Suffix"        },
                      {"type":"ST", "desc":"Prefix"        }]},
                "CQ":{
                   "desc":"Composite Quantity with Units",
                   "type":"composite",
                   "children":[
                      {"type":"NM", "desc":"Quantity"},
                      {"type":"CE", "desc":"Units"   }]},
                "DFTP03":{
                   "desc":"Post detail financial transaction",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"         ,"req":true},
                      {"type":"EVN", "desc":"Event Type"             ,"req":true},
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"         },
                      {"type":"FT1", "desc":"Financial Transaction"  ,"repeats":true}]},
                "DG1":{
                   "desc":"Diagnosis",
                   "type":"segment",
                   "children":[
                      {"type":"SI", "desc":"Set ID - Diagnosis"        ,"req":true},
                      {"type":"ID", "desc":"Diagnosis Coding Method"   ,"req":true},
                      {"type":"ID", "desc":"Diagnosis Code"           },
                      {"type":"ST", "desc":"Diagnosis Description"    },
                      {"type":"TS", "desc":"Diagnosis Date/Time"      },
                      {"type":"ID", "desc":"Diagnosis/DRG Type"        ,"req":true},
                      {"type":"ST", "desc":"Major Diagnostic Category"},
                      {"type":"ID", "desc":"Diagnostic Related Group" },
                      {"type":"ID", "desc":"DRG Approval Indicator"   },
                      {"type":"ID", "desc":"DRG Grouper Review Code"  },
                      {"type":"ID", "desc":"Outlier Type"             },
                      {"type":"NM", "desc":"Outlier Days"             },
                      {"type":"NM", "desc":"Outlier Cost"             },
                      {"type":"ST", "desc":"Grouper Version and Type" }]},
                "DSC":{
                   "desc":"Continuation Pointer",
                   "type":"segment",
                   "children":[
                      {"type":"ST", "desc":"Continuation Pointer"}]},
                "DSP":{
                   "desc":"Display Data",
                   "type":"segment",
                   "children":[
                      {"type":"SI", "desc":"Set ID - Display Data"},
                      {"type":"SI", "desc":"Display Level"        },
                      {"type":"TX", "desc":"Data Line"             ,"req":true},
                      {"type":"ST", "desc":"Logical Break Point"  },
                      {"type":"TX", "desc":"Result ID"            }]},
                "DSR":{
                   "desc":"No description.",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"                  ,"req":true},
                      {"type":"MSA", "desc":"Message Acknowledgement"        },
                      {"type":"QRD", "desc":"Original Style Query Definition" ,"req":true},
                      {"type":"QRF", "desc":"Original style Query filter"    },
                      {"type":"DSP", "desc":"Display Data"                    ,"req":true ,"repeats":true},
                      {"type":"DSC", "desc":"Continuation Pointer"            ,"req":true}]},
                "DT":{
                   "desc":"Date",
                   "type":"composite"
                },
                "ERR":{
                   "desc":"Error",
                   "type":"segment",
                   "children":[
                      {"type":"ID", "desc":"Error Code and Location" ,"req":true}]},
                "EVN":{
                   "desc":"Event Type",
                   "type":"segment",
                   "children":[
                      {"type":"ID", "desc":"Event Type Code"         ,"req":true},
                      {"type":"TS", "desc":"Date/Time of Event"      ,"req":true},
                      {"type":"TS", "desc":"Date/Time Planned Event"},
                      {"type":"ID", "desc":"Event Reason Code"      }]},
                "FHS":{
                   "desc":"File Header",
                   "type":"segment",
                   "children":[
                      {"type":"ST", "desc":"File Field Separators"    ,"req":true},
                      {"type":"ST", "desc":"File Encoding Characters" ,"req":true},
                      {"type":"ST", "desc":"File Sending Application"},
                      {"type":"ST", "desc":"File Sending Facility"   },
                      {"type":"ST", "desc":"File Rcving Application" },
                      {"type":"ST", "desc":"File Receiving Facility" },
                      {"type":"TS", "desc":"File Creation Date/Time" },
                      {"type":"ST", "desc":"File Security"           },
                      {"type":"ST", "desc":"File Name/ID/Type"       },
                      {"type":"ST", "desc":"File Comment"            },
                      {"type":"ST", "desc":"File Control ID"         },
                      {"type":"ST", "desc":"Reference File Cntrl ID" }]},
                "FT1":{
                   "desc":"Financial Transaction",
                   "type":"segment",
                   "children":[
                      {"type":"SI", "desc":"Set ID - Financial Trans" },
                      {"type":"ST", "desc":"Transaction ID"           },
                      {"type":"ST", "desc":"Transaction Batch ID"     },
                      {"type":"DT", "desc":"Transaction Date"          ,"req":true},
                      {"type":"DT", "desc":"Transaction Posting Date" },
                      {"type":"ID", "desc":"Transaction Type"          ,"req":true},
                      {"type":"ID", "desc":"Transaction Code"          ,"req":true},
                      {"type":"ST", "desc":"Transaction Description"  },
                      {"type":"ST", "desc":"Transaction Desc. - Alt"  },
                      {"type":"NM", "desc":"Transaction Quantity"     },
                      {"type":"NM", "desc":"Transaction Amount - Ext."},
                      {"type":"NM", "desc":"Transaction Amount - Unit"},
                      {"type":"ST", "desc":"Department Code"          },
                      {"type":"ID", "desc":"Insurance Plan ID"        },
                      {"type":"NM", "desc":"Insurance Amount"         },
                      {"type":"ST", "desc":"Patient Location"         },
                      {"type":"ID", "desc":"Fee Schedule"             },
                      {"type":"ID", "desc":"Patient Type"             },
                      {"type":"ID", "desc":"Diagnosis Code"           },
                      {"type":"CN", "desc":"Performed by Code"        },
                      {"type":"CN", "desc":"Ordered by Code"          },
                      {"type":"NM", "desc":"Unit Cost"                }]},
                "FTS":{
                   "desc":"File Trailer",
                   "type":"segment",
                   "children":[
                      {"type":"ST", "desc":"File Batch Count"    },
                      {"type":"CM", "desc":"File Trailer Comment"}]},
                "GRP1":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"PID",  "desc":"Patient Identification"},
                      {"type":"NTE",  "desc":"Notes and Comments"     ,"repeats":true},
                      {"type":"GRP2", "desc":""                       ,"req":true ,"repeats":true}]},
                "GRP1_ADTA17":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"          ,"req":true}]},
                "GRP1_BARP01":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"PV1", "desc":"Patient Visit"                 },
                      {"type":"DG1", "desc":"Diagnosis"                      ,"repeats":true},
                      {"type":"PR1", "desc":"Procedures"                     ,"repeats":true},
                      {"type":"GT1", "desc":"Guarantor"                      ,"repeats":true},
                      {"type":"NK1", "desc":"Next of Kin/Associated Parties" ,"repeats":true},
                      {"type":"IN1", "desc":"Insurance"                      ,"repeats":true},
                      {"type":"ACC", "desc":"Accident"                      },
                      {"type":"UB1", "desc":"UB82 Data"                     }]},
                "GRP1_BARP02":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"PV1", "desc":"Patient Visit"         }]},
                "GRP1_ORF":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"QRD",      "desc":"Original Style Query Definition" ,"req":true},
                      {"type":"QRF",      "desc":"Original style Query filter"    },
                      {"type":"PID",      "desc":"Patient Identification"         },
                      {"type":"NTE",      "desc":"Notes and Comments"              ,"repeats":true},
                      {"type":"GRP2_ORF", "desc":""                                ,"req":true ,"repeats":true}]},
                "GRP1_ORMO01":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"NTE", "desc":"Notes and Comments"     ,"repeats":true},
                      {"type":"PV1", "desc":"Patient Visit"         }]},
                "GRP1_ORUR01":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"GRP2_ORUR01", "desc":""},
                      {"type":"GRP3_ORUR01", "desc":"" ,"req":true ,"repeats":true}]},
                "GRP2":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"ORC",  "desc":"Common Order"       ,"req":true},
                      {"type":"GRP3", "desc":""                   ,"repeats":true},
                      {"type":"NTE",  "desc":"Notes and Comments" ,"repeats":true}]},
                "GRP2_ORF":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"ORC",      "desc":"Common Order"       },
                      {"type":"OBR",      "desc":"Observation Request" ,"req":true},
                      {"type":"NTE",      "desc":"Notes and Comments"  ,"repeats":true},
                      {"type":"GRP3_ORF", "desc":""                    ,"req":true ,"repeats":true}]},
                "GRP2_ORMO01":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"ORC",         "desc":"Common Order" ,"req":true},
                      {"type":"GRP3_ORMO01", "desc":""            },
                      {"type":"BLG",         "desc":"Billing"     }]},
                "GRP2_ORUR01":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"PID", "desc":"Patient Identification" ,"req":true},
                      {"type":"NTE", "desc":"Notes and Comments"     ,"repeats":true},
                      {"type":"PV1", "desc":"Patient Visit"         }]},
                "GRP3":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"ORO", "desc":"No description"      ,"req":true},
                      {"type":"OBR", "desc":"Observation Request" ,"req":true},
                      {"type":"RX1", "desc":"No description"      ,"req":true}]},
                "GRP3_ORF":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"OBX", "desc":"Observation/Result"},
                      {"type":"NTE", "desc":"Notes and Comments" ,"repeats":true}]},
                "GRP3_ORMO01":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"GRP4", "desc":""                   ,"req":true ,"repeats":true},
                      {"type":"NTE",  "desc":"Notes and Comments" ,"repeats":true},
                      {"type":"GRP5", "desc":""                   ,"repeats":true}]},
                "GRP3_ORUR01":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"ORC",         "desc":"Common Order"       },
                      {"type":"OBR",         "desc":"Observation Request" ,"req":true},
                      {"type":"NTE",         "desc":"Notes and Comments"  ,"repeats":true},
                      {"type":"GRP4_ORUR01", "desc":""                    ,"req":true ,"repeats":true}]},
                "GRP4":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"ORO", "desc":"No description"      ,"req":true},
                      {"type":"OBR", "desc":"Observation Request" ,"req":true},
                      {"type":"RX1", "desc":"No description"      ,"req":true}]},
                "GRP4_ORUR01":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"OBX", "desc":"Observation/Result"},
                      {"type":"NTE", "desc":"Notes and Comments" ,"repeats":true}]},
                "GRP5":{
                   "desc":"",
                   "type":"segment_group",
                   "children":[
                      {"type":"OBX", "desc":"Observation/Result" ,"req":true},
                      {"type":"NTE", "desc":"Notes and Comments" ,"repeats":true}]},
                "GT1":{
                   "desc":"Guarantor",
                   "type":"segment",
                   "children":[
                      {"type":"SI", "desc":"Set ID - Guarantor"        ,"req":true},
                      {"type":"ID", "desc":"Guarantor Number"         },
                      {"type":"PN", "desc":"Guarantor Name"            ,"req":true},
                      {"type":"PN", "desc":"Guarantor Spouse Name"    },
                      {"type":"AD", "desc":"Guarantor Address"        },
                      {"type":"TN", "desc":"Guarantor Phone - Home"   },
                      {"type":"TN", "desc":"Guarantor Phone - Bus."   },
                      {"type":"DT", "desc":"Guarantor Date of Birth"  },
                      {"type":"ID", "desc":"Guarantor Sex"            },
                      {"type":"ID", "desc":"Guarantor Type"           },
                      {"type":"ID", "desc":"Guarantor Relationship"   },
                      {"type":"ST", "desc":"Guarantor SSN"            },
                      {"type":"DT", "desc":"Guarantor Date - Begin"   },
                      {"type":"DT", "desc":"Guarantor Date - End"     },
                      {"type":"NM", "desc":"Guarantor Priority"       },
                      {"type":"ST", "desc":"Guarantor Employer Name"  },
                      {"type":"AD", "desc":"Guarantor Employer Addr"  },
                      {"type":"TN", "desc":"Guarantor Employer Phone" },
                      {"type":"ST", "desc":"Guarantor Employee ID #"  },
                      {"type":"ID", "desc":"Guarantor Employmt Status"}]},
                "ID":{
                   "desc":"ID Field",
                   "type":"composite"
                },
                "IN1":{
                   "desc":"Insurance",
                   "type":"segment",
                   "children":[
                      {"type":"SI", "desc":"Set ID - Insurance"        ,"req":true},
                      {"type":"ID", "desc":"Insurance Plan ID"         ,"req":true},
                      {"type":"ST", "desc":"Insurance Company ID"      ,"req":true},
                      {"type":"ST", "desc":"Insurance Company Name"   },
                      {"type":"AD", "desc":"Insurance Company Address"},
                      {"type":"PN", "desc":"Insurance Co Contact Pers"},
                      {"type":"TN", "desc":"Insurance Co Phone Number"},
                      {"type":"ST", "desc":"Group Number"             },
                      {"type":"ST", "desc":"Group Name"               },
                      {"type":"ST", "desc":"Insured's Group Emp. ID"  },
                      {"type":"ST", "desc":"Insured's Group Emp. Name"},
                      {"type":"DT", "desc":"Plan Effective Date"      },
                      {"type":"DT", "desc":"Plan Expiration Date"     },
                      {"type":"ST", "desc":"Authorization Information"},
                      {"type":"ID", "desc":"Plan Type"                },
                      {"type":"PN", "desc":"Name of Insured"          },
                      {"type":"ID", "desc":"Insured's Relation to Pat"},
                      {"type":"DT", "desc":"Insured's Date of Birth"  },
                      {"type":"AD", "desc":"Insured's Address"        },
                      {"type":"ID", "desc":"Assignment of Benefits"   },
                      {"type":"ID", "desc":"Coordination of Benefits" },
                      {"type":"ST", "desc":"Coord. of Ben. Priority"  },
                      {"type":"ID", "desc":"Notice of Admission Code" },
                      {"type":"DT", "desc":"Notice of Admission Date" },
                      {"type":"ID", "desc":"Rpt of Eligibility Code"  },
                      {"type":"DT", "desc":"Rpt of Eligibility Date"  },
                      {"type":"ID", "desc":"Release Information Code" },
                      {"type":"ST", "desc":"Pre-Admit Cert. (PAC)"    },
                      {"type":"DT", "desc":"Verification Date"        },
                      {"type":"CM", "desc":"Verification By"          },
                      {"type":"ID", "desc":"Type of Agreement Code"   },
                      {"type":"ID", "desc":"Billing Status"           },
                      {"type":"NM", "desc":"Lifetime Reserve Days"    },
                      {"type":"NM", "desc":"Delay Before L. R. Day"   },
                      {"type":"ST", "desc":"Company Plan Code"        },
                      {"type":"ST", "desc":"Policy Number"            },
                      {"type":"NM", "desc":"Policy Deductible"        },
                      {"type":"NM", "desc":"Policy Limit - Amount"    },
                      {"type":"NM", "desc":"Policy Limit - Days"      },
                      {"type":"NM", "desc":"Room Rate - Semi-Private" },
                      {"type":"NM", "desc":"Room Rate - Private"      },
                      {"type":"ID", "desc":"Insured's Employ Status"  },
                      {"type":"ID", "desc":"Insured's Sex"            },
                      {"type":"AD", "desc":"Insured's Employer Addr"  }]},
                "MCF":{
                   "desc":"No description.",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"          ,"req":true},
                      {"type":"MSA", "desc":"Message Acknowledgement" ,"req":true}]},
                "MRG":{
                   "desc":"Merge Patient Information",
                   "type":"segment",
                   "children":[
                      {"type":"CK", "desc":"Prior Patient ID - Int"  ,"req":true},
                      {"type":"CK", "desc":"Prior Alt Patient ID"   },
                      {"type":"ST", "desc":"Prior Patient Account #"}]},
                "MSA":{
                   "desc":"Message Acknowledgement",
                   "type":"segment",
                   "children":[
                      {"type":"ID", "desc":"Acknowledgement Code"     ,"req":true},
                      {"type":"ST", "desc":"Message Control ID"       ,"req":true},
                      {"type":"ST", "desc":"Text Message"            },
                      {"type":"NM", "desc":"Expected Sequence Number"},
                      {"type":"ID", "desc":"Delayed Ack Type"        }]},
                "MSH":{
                   "desc":"Message Header",
                   "type":"segment",
                   "children":[
                      {"type":"ST", "desc":"Field Separator"       ,"req":true},
                      {"type":"ST", "desc":"Encoding Characters"   ,"req":true},
                      {"type":"ST", "desc":"Sending Application"  },
                      {"type":"ST", "desc":"Sending Facility"     },
                      {"type":"ST", "desc":"Receiving Application"},
                      {"type":"ST", "desc":"Receiving Facility"   },
                      {"type":"TS", "desc":"Date/Time of Message" },
                      {"type":"ST", "desc":"Security"             },
                      {"type":"CM", "desc":"Message Type"          ,"req":true},
                      {"type":"ST", "desc":"Message Control ID"    ,"req":true},
                      {"type":"ID", "desc":"Processing ID"         ,"req":true},
                      {"type":"NM", "desc":"Version ID"            ,"req":true},
                      {"type":"NM", "desc":"Sequence Number"      },
                      {"type":"ST", "desc":"Continuation Pointer" }]},
                "NACK":{
                   "desc":"Negative acknowledgment",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"          ,"req":true},
                      {"type":"MSA", "desc":"Message Acknowledgement" ,"req":true},
                      {"type":"ERR", "desc":"Error"                  }]},
                "NK1":{
                   "desc":"Next of Kin/Associated Parties",
                   "type":"segment",
                   "children":[
                      {"type":"SI", "desc":"Set ID - Next of Kin"     ,"req":true},
                      {"type":"PN", "desc":"Next of Kin Name"        },
                      {"type":"ST", "desc":"Next of Kin Relationship"},
                      {"type":"AD", "desc":"Next of Kin Address"     },
                      {"type":"TN", "desc":"Next of Kin Phone Number" ,"repeats":true}]},
                "NM":{
                   "desc":"Numeric",
                   "type":"composite"
                },
                "NPU":{
                   "desc":"Bed Status Update",
                   "type":"segment",
                   "children":[
                      {"type":"ID", "desc":"Bed location" ,"req":true},
                      {"type":"ID", "desc":"Bed Status"  }]},
                "NTE":{
                   "desc":"Notes and Comments",
                   "type":"segment",
                   "children":[
                      {"type":"SI", "desc":"Set ID"           },
                      {"type":"ID", "desc":"Source of Comment"},
                      {"type":"TX", "desc":"Comment"           ,"req":true ,"repeats":true}]},
                "OBR":{
                   "desc":"Observation Request",
                   "type":"segment",
                   "children":[
                      {"type":"SI", "desc":"Set Id"                   },
                      {"type":"CM", "desc":"Placer Orders #"          },
                      {"type":"CM", "desc":"Fillers Order #"          },
                      {"type":"CE", "desc":"Universal Service ID"      ,"req":true},
                      {"type":"ST", "desc":"Priority"                 },
                      {"type":"TS", "desc":"Requested Date/Time"      },
                      {"type":"TS", "desc":"Observation Date/Time"     ,"req":true},
                      {"type":"TS", "desc":"Observation End Date/Time" ,"req":true},
                      {"type":"CQ", "desc":"Collection Volume"         ,"req":true},
                      {"type":"CN", "desc":"Collector Identifier"      ,"repeats":true},
                      {"type":"ST", "desc":"Specimen Action Code"     },
                      {"type":"CM", "desc":"Danger Code"              },
                      {"type":"ST", "desc":"Relevant Clinical Info."  },
                      {"type":"TS", "desc":"Specimen Rcvd Date/Time"   ,"req":true},
                      {"type":"CM", "desc":"Specimen Source"          },
                      {"type":"CN", "desc":"Ordering Provider"         ,"repeats":true},
                      {"type":"TN", "desc":"Order Call Back Phone Num" ,"repeats":true},
                      {"type":"ST", "desc":"Placers Field #1"         },
                      {"type":"ST", "desc":"Placers Field #2"         },
                      {"type":"ST", "desc":"Fillers Field #1"         },
                      {"type":"ST", "desc":"Fillers Field #2"         },
                      {"type":"TS", "desc":"Results Rpt/Status Chg-dt" ,"req":true},
                      {"type":"CM", "desc":"Charge to Practice"       },
                      {"type":"ID", "desc":"Diagnostic Serv Sect Id"  },
                      {"type":"ID", "desc":"Result Status"            },
                      {"type":"CE", "desc":"Linked Results"           },
                      {"type":"CM", "desc":"Quantity/Timing"           ,"repeats":true},
                      {"type":"CN", "desc":"Result Copies to"          ,"repeats":true},
                      {"type":"CM", "desc":"Parent Accession #"       },
                      {"type":"ID", "desc":"Transportation Mode"      },
                      {"type":"CE", "desc":"Reason for Study"          ,"repeats":true},
                      {"type":"CN", "desc":"Prin Result Interpreter"  },
                      {"type":"CN", "desc":"Asst Result Interpreter"  },
                      {"type":"CN", "desc":"Technician"               },
                      {"type":"CN", "desc":"Transcriptionist"         },
                      {"type":"TS", "desc":"Scheduled Date/Time"      }]},
                "OBX":{
                   "desc":"Observation/Result",
                   "type":"segment",
                   "children":[
                      {"type":"SI", "desc":"Set Id"                 },
                      {"type":"ID", "desc":"Value Type"             },
                      {"type":"CE", "desc":"Observation Identifier"  ,"req":true},
                      {"type":"ST", "desc":"Observation Sub-Id"     },
                      {"type":"ST", "desc":"Observation Results"     ,"req":true},
                      {"type":"ST", "desc":"Units"                  },
                      {"type":"ST", "desc":"Reference Range"        },
                      {"type":"ST", "desc":"Abnormal Flags"          ,"repeats":true},
                      {"type":"NM", "desc":"Probability"            },
                      {"type":"ID", "desc":"Nature of Abnormal Test"},
                      {"type":"ID", "desc":"Observ Result Status"   },
                      {"type":"TS", "desc":"Date Last Normal Value" }]},
                "ORC":{
                   "desc":"Common Order",
                   "type":"segment",
                   "children":[
                      {"type":"ST", "desc":"Order Control"            ,"req":true},
                      {"type":"CM", "desc":"Placer Order #"          },
                      {"type":"CM", "desc":"Filler Order #"          },
                      {"type":"CM", "desc":"Placer Order #"          },
                      {"type":"ST", "desc":"Order Status"            },
                      {"type":"ST", "desc":"Response Flag"           },
                      {"type":"CM", "desc":"Timing/Quantity"         },
                      {"type":"CM", "desc":"Parent"                  },
                      {"type":"TS", "desc":"Date/Time of Transaction"},
                      {"type":"CN", "desc":"Enterted BY"             },
                      {"type":"CN", "desc":"Verified By"             },
                      {"type":"CN", "desc":"Ordering Provider"       },
                      {"type":"CM", "desc":"Enterer's Location"      },
                      {"type":"TN", "desc":"Call Back Phone Number"   ,"repeats":true}]},
                "ORF":{
                   "desc":"No description.",
                   "type":"message",
                   "children":[
                      {"type":"MSH",      "desc":"Message Header"          ,"req":true},
                      {"type":"MSA",      "desc":"Message Acknowledgement" ,"req":true},
                      {"type":"GRP1_ORF", "desc":""                        ,"req":true ,"repeats":true},
                      {"type":"DSC",      "desc":"Continuation Pointer"   }]},
                "ORM":{
                   "desc":"No description.",
                   "type":"message",
                   "children":[
                      {"type":"MSH",         "desc":"Message Header"     ,"req":true},
                      {"type":"NTE",         "desc":"Notes and Comments" ,"repeats":true},
                      {"type":"GRP1_ORMO01", "desc":""                  },
                      {"type":"GRP2_ORMO01", "desc":""                   ,"req":true ,"repeats":true}]},
                "ORMO01":{
                   "desc":"Order Message",
                   "type":"message",
                   "children":[
                      {"type":"MSH",         "desc":"Message Header"     ,"req":true},
                      {"type":"NTE",         "desc":"Notes and Comments" ,"repeats":true},
                      {"type":"GRP1_ORMO01", "desc":""                  },
                      {"type":"GRP2_ORMO01", "desc":""                   ,"req":true ,"repeats":true}]},
                "ORO":{
                   "desc":"No description",
                   "type":"segment",
                   "children":[
                      {"type":"CE", "desc":"Order Item Id"     },
                      {"type":"ID", "desc":"Substitute Allowed"},
                      {"type":"CN", "desc":"Results Copied To"  ,"repeats":true},
                      {"type":"ID", "desc":"Stock Location"    }]},
                "ORR":{
                   "desc":"No description.",
                   "type":"message",
                   "children":[
                      {"type":"MSH",  "desc":"Message Header"          ,"req":true},
                      {"type":"MSA",  "desc":"Message Acknowledgement" ,"req":true},
                      {"type":"NTE",  "desc":"Notes and Comments"      ,"repeats":true},
                      {"type":"GRP1", "desc":""                       }]},
                "ORUR01":{
                   "desc":"[P,F] Observations to follow",
                   "type":"message",
                   "children":[
                      {"type":"MSH",         "desc":"Message Header"          ,"req":true},
                      {"type":"MSA",         "desc":"Message Acknowledgement" ,"req":true},
                      {"type":"GRP1_ORUR01", "desc":""                        ,"req":true ,"repeats":true},
                      {"type":"DSC",         "desc":"Continuation Pointer"   }]},
                "PID":{
                   "desc":"Patient Identification",
                   "type":"segment",
                   "children":[
                      {"type":"SI", "desc":"Set ID - Patient ID"      },
                      {"type":"CK", "desc":"Patient ID (External ID)" },
                      {"type":"CK", "desc":"Patient ID (Internal ID)"  ,"req":true},
                      {"type":"ST", "desc":"Alternate Patient ID"     },
                      {"type":"PN", "desc":"Patient's Name"            ,"req":true},
                      {"type":"ST", "desc":"Mother's Maiden Name"     },
                      {"type":"DT", "desc":"Date of Birth"            },
                      {"type":"ID", "desc":"Sex"                      },
                      {"type":"PN", "desc":"Patient Alias"             ,"repeats":true},
                      {"type":"ID", "desc":"Ethnic Group"             },
                      {"type":"AD", "desc":"Patient Address"          },
                      {"type":"ID", "desc":"County Code"              },
                      {"type":"TN", "desc":"Phone Number - Home"      },
                      {"type":"TN", "desc":"Phone Number - Business"  },
                      {"type":"ST", "desc":"Language - Patient"       },
                      {"type":"ID", "desc":"Marital Status"           },
                      {"type":"ID", "desc":"Religion"                 },
                      {"type":"CK", "desc":"Patient Account Number"   },
                      {"type":"ST", "desc":"SSN Number - Patient"     },
                      {"type":"CM", "desc":"Drivers License - Patient"}]},
                "PN":{
                   "desc":"Person Name",
                   "type":"composite"
                },
                "PR1":{
                   "desc":"Procedures",
                   "type":"segment",
                   "children":[
                      {"type":"SI", "desc":"Set ID - Procedure"      ,"req":true ,"repeats":true},
                      {"type":"ID", "desc":"Procedure Coding Method" ,"req":true ,"repeats":true},
                      {"type":"ID", "desc":"Procedure Code"          ,"req":true ,"repeats":true},
                      {"type":"ST", "desc":"Procedure Description"   ,"repeats":true},
                      {"type":"TS", "desc":"Procedure Date/Time"     ,"req":true},
                      {"type":"ID", "desc":"Procedure Type"          ,"req":true},
                      {"type":"NM", "desc":"Procedure Minutes"      },
                      {"type":"CN", "desc":"Anesthesiologist"       },
                      {"type":"ID", "desc":"Anesthesia Code"        },
                      {"type":"NM", "desc":"Anesthesia Minutes"     },
                      {"type":"CN", "desc":"Surgeon"                },
                      {"type":"CN", "desc":"Resident Code"          },
                      {"type":"ID", "desc":"Consent Code"           }]},
                "PV1":{
                   "desc":"Patient Visit",
                   "type":"segment",
                   "children":[
                      {"type":"SI", "desc":"Set Id"                   },
                      {"type":"ID", "desc":"Patient Class"             ,"req":true},
                      {"type":"ID", "desc":"Assigned Patient Location" ,"req":true},
                      {"type":"ID", "desc":"Admission Type"           },
                      {"type":"ST", "desc":"Pre-Admit Number"         },
                      {"type":"ID", "desc":"Prior Patient Location"   },
                      {"type":"CN", "desc":"Attending Doctor"         },
                      {"type":"CN", "desc":"Refering Doctor"          },
                      {"type":"CN", "desc":"Consulting Doctor"         ,"repeats":true},
                      {"type":"ID", "desc":"Hospital Service"         },
                      {"type":"ID", "desc":"Temporary Location"       },
                      {"type":"ID", "desc":"Pre-Admit Test Indicator" },
                      {"type":"ID", "desc":"Re-Admission Indicator"   },
                      {"type":"ID", "desc":"Admit Source"             },
                      {"type":"ID", "desc":"Ambulatory Status"        },
                      {"type":"ID", "desc":"VIP Indicators"           },
                      {"type":"CN", "desc":"Admitting Doctor"         },
                      {"type":"ID", "desc":"Patient Type"             },
                      {"type":"NM", "desc":"Visit Number"             },
                      {"type":"ID", "desc":"Financial Class"          },
                      {"type":"ID", "desc":"Charge Price Indicator"   },
                      {"type":"ID", "desc":"Courtesy Code"            },
                      {"type":"ID", "desc":"Credit Rating"            },
                      {"type":"ID", "desc":"Contract Code"             ,"repeats":true},
                      {"type":"DT", "desc":"Contract Effective Date"   ,"repeats":true},
                      {"type":"NM", "desc":"Contract Amount"           ,"repeats":true},
                      {"type":"NM", "desc":"Contract Period"           ,"repeats":true},
                      {"type":"ID", "desc":"Interest Code"            },
                      {"type":"ID", "desc":"Transfer to Bad Debt Code"},
                      {"type":"DT", "desc":"Transfer to Bad Debt Date"},
                      {"type":"ST", "desc":"Bad Debt Agency Code"     },
                      {"type":"NM", "desc":"Bad Debt Transfer Amount" },
                      {"type":"NM", "desc":"Bad Debt Recovery Amount" },
                      {"type":"ID", "desc":"Delete Account Indicator" },
                      {"type":"DT", "desc":"Delete Account Date"      },
                      {"type":"ID", "desc":"Discharge Disposition"    },
                      {"type":"ID", "desc":"Discharged to Location"   },
                      {"type":"ID", "desc":"Diet Type"                },
                      {"type":"ID", "desc":"Servicing Facility"       },
                      {"type":"ID", "desc":"Bed Status"               },
                      {"type":"ID", "desc":"Account Status"           },
                      {"type":"ID", "desc":"Pending Location"         },
                      {"type":"ID", "desc":"Prior Temporary Location" },
                      {"type":"TS", "desc":"Admit Date/Time"          },
                      {"type":"TS", "desc":"Discharge Date/Time"      },
                      {"type":"NM", "desc":"Current Patient Balance"  },
                      {"type":"NM", "desc":"Total Charges"            },
                      {"type":"NM", "desc":"Total Adjustments"        },
                      {"type":"NM", "desc":"Total Payments"           }]},
                "QRD":{
                   "desc":"Original Style Query Definition",
                   "type":"segment",
                   "children":[
                      {"type":"TS", "desc":"Query Date/Time"          ,"req":true},
                      {"type":"ID", "desc":"Query Format Code"        ,"req":true},
                      {"type":"ID", "desc":"Query Priority"           ,"req":true},
                      {"type":"ST", "desc":"Query ID"                 ,"req":true},
                      {"type":"ID", "desc":"Deferred Response Type"  },
                      {"type":"TS", "desc":"Def. Resp. Date/Time"    },
                      {"type":"CQ", "desc":"Quantity Limited Request" ,"req":true},
                      {"type":"ST", "desc":"Who Subject Filter"       ,"req":true ,"repeats":true},
                      {"type":"ID", "desc":"What Subject Filter"      ,"req":true ,"repeats":true},
                      {"type":"ST", "desc":"What Dept. Data Code"     ,"req":true ,"repeats":true},
                      {"type":"ST", "desc":"What data Cd. Value Qua." ,"repeats":true},
                      {"type":"ID", "desc":"Query Results Level"     }]},
                "QRF":{
                   "desc":"Original style Query filter",
                   "type":"segment",
                   "children":[
                      {"type":"ST", "desc":"Where Subject Filter"      ,"req":true ,"repeats":true},
                      {"type":"TS", "desc":"When Data Start Date/Time"},
                      {"type":"TS", "desc":"When Data End Date/Time"  },
                      {"type":"ST", "desc":"What User Qualifier"       ,"repeats":true},
                      {"type":"ST", "desc":"Other Qry Subject Filter"  ,"repeats":true}]},
                "QRYQ01":{
                   "desc":"Query for immediate response",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"                  ,"req":true},
                      {"type":"QRD", "desc":"Original Style Query Definition" ,"req":true},
                      {"type":"QRF", "desc":"Original style Query filter"    },
                      {"type":"DSC", "desc":"Continuation Pointer"            ,"req":true}]},
                "QRYQ03":{
                   "desc":"No description.",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"                  ,"req":true},
                      {"type":"QRD", "desc":"Original Style Query Definition" ,"req":true},
                      {"type":"QRF", "desc":"Original style Query filter"    },
                      {"type":"DSC", "desc":"Continuation Pointer"            ,"req":true}]},
                "QRYQ05":{
                   "desc":"No description.",
                   "type":"message",
                   "children":[
                      {"type":"MSH", "desc":"Message Header"            ,"req":true},
                      {"type":"URD", "desc":"Results/Update Definition" ,"req":true},
                      {"type":"URS", "desc":"Unsolicited Selection"    },
                      {"type":"DSP", "desc":"Display Data"              ,"req":true ,"repeats":true},
                      {"type":"DSC", "desc":"Continuation Pointer"      ,"req":true}]},
                "RX1":{
                   "desc":"No description",
                   "type":"segment",
                   "children":[
                      {"type":"UN", "desc":"Unused"                   },
                      {"type":"UN", "desc":"Unused"                   },
                      {"type":"ST", "desc":"Route"                    },
                      {"type":"ST", "desc":"Site Administered"        },
                      {"type":"CQ", "desc":"IV Solution Rate"         },
                      {"type":"CQ", "desc":"Drug Strength"            },
                      {"type":"NM", "desc":"Final Concentration"      },
                      {"type":"NM", "desc":"Final Volume in Ml."      },
                      {"type":"CM", "desc":"Drug Dose"                },
                      {"type":"ID", "desc":"Drug Role"                },
                      {"type":"NM", "desc":"Prescription Sequence Num"},
                      {"type":"CQ", "desc":"Quantity Dispensed"       },
                      {"type":"UN", "desc":"Unused"                   },
                      {"type":"CE", "desc":"Drug ID"                  },
                      {"type":"ID", "desc":"Component Drug IDs"        ,"repeats":true},
                      {"type":"ID", "desc":"Prescription Type"        },
                      {"type":"ID", "desc":"Substitution Status"      },
                      {"type":"ID", "desc":"Rx Order Status"          },
                      {"type":"NM", "desc":"Number of Refills"        },
                      {"type":"UN", "desc":"Unused"                   },
                      {"type":"NM", "desc":"Refills Remaining"        },
                      {"type":"ID", "desc":"DEA Class"                },
                      {"type":"NM", "desc":"Ordering Md's DEA Number" },
                      {"type":"UN", "desc":"Unused"                   },
                      {"type":"TS", "desc":"Last Refill Date/Time"    },
                      {"type":"ST", "desc":"RX Number"                },
                      {"type":"ID", "desc":"PRN Status"               },
                      {"type":"TX", "desc":"Pharmacy Instructions"     ,"repeats":true},
                      {"type":"TX", "desc":"Patient Instruction"       ,"repeats":true},
                      {"type":"TX", "desc":"Instructions (SIG)"        ,"repeats":true}]},
                "SI":{
                   "desc":"Sequence ID",
                   "type":"composite"
                },
                "ST":{
                   "desc":"String",
                   "type":"composite"
                },
                "TN":{
                   "desc":"Telephone Number",
                   "type":"composite"
                },
                "TS":{
                   "desc":"Time stamp",
                   "type":"composite"
                },
                "TX":{
                   "desc":"Text",
                   "type":"composite"
                },
                "UB1":{
                   "desc":"UB82 Data",
                   "type":"segment",
                   "children":[
                      {"type":"SI", "desc":"Set ID - UB82"            },
                      {"type":"ST", "desc":"Blood Deductible"         },
                      {"type":"ST", "desc":"Blood Furn.-Pints of (40)"},
                      {"type":"ST", "desc":"Blook Replaced-Pints (41)"},
                      {"type":"ST", "desc":"Blood Not Rplcd-Pints(42)"},
                      {"type":"ST", "desc":"Co-Insurance Days (25)"   },
                      {"type":"ID", "desc":"Condition Code"            ,"repeats":true},
                      {"type":"ST", "desc":"Covered Days (23)"        },
                      {"type":"ST", "desc":"Non-Covered Days (24)"    },
                      {"type":"CM", "desc":"Value Amount & Code"       ,"repeats":true},
                      {"type":"ST", "desc":"Number of Grace Days (90)"},
                      {"type":"ID", "desc":"Spec. Prog. Indicator(44)"},
                      {"type":"ID", "desc":"PSRO/UR Approvl Ind. (87)"},
                      {"type":"DT", "desc":"PSRO/UR Aprvd Stay-Fm(88)"},
                      {"type":"DT", "desc":"PSRO/UR Aprvd Stay-To(89)"},
                      {"type":"ID", "desc":"Occurrence (28-32)"        ,"repeats":true},
                      {"type":"ID", "desc":"Occurrence Span (33)"     },
                      {"type":"DT", "desc":"Occur Span Start Date(33)"},
                      {"type":"DT", "desc":"Occur Span End Date (33)" },
                      {"type":"ST", "desc":"UB-82 Locator 2"          },
                      {"type":"ST", "desc":"UB-82 Locator 9"          },
                      {"type":"ST", "desc":"UB-82 Locator 27"         },
                      {"type":"ST", "desc":"UB-82 Locator 45"         }]},
                "UN":{
                   "desc":"Unused",
                   "type":"composite"
                },
                "URD":{
                   "desc":"Results/Update Definition",
                   "type":"segment",
                   "children":[
                      {"type":"SI", "desc":"R/U Date/Time"            },
                      {"type":"CK", "desc":"Report Priority"          },
                      {"type":"CK", "desc":"R/U Who Subject Defnition" ,"req":true ,"repeats":true},
                      {"type":"ST", "desc":"R/U What Subject Defntion" ,"repeats":true},
                      {"type":"PN", "desc":"R/U What Department Code"  ,"repeats":true},
                      {"type":"ST", "desc":"R/U Display/Print Locs"    ,"repeats":true},
                      {"type":"DT", "desc":"R/U Results Level"        }]},
                "URS":{
                   "desc":"Unsolicited Selection",
                   "type":"segment",
                   "children":[
                      {"type":"ST", "desc":"R/U Where Subject Def."  ,"req":true ,"repeats":true},
                      {"type":"TS", "desc":"R/U When Start Dte/Tme" },
                      {"type":"TS", "desc":"R/U When End Dte/Tme"   },
                      {"type":"ST", "desc":"R/U What User Qualifier" ,"repeats":true},
                      {"type":"ST", "desc":"R/U Oth Results Def."    ,"repeats":true}]}},
             "matching":[
                {"rule":"ORR*"   , "name":"ORR"   },
                {"rule":"ORM^O01", "name":"ORMO01"},
                {"rule":"ACK*"   , "name":"ACK"   },
                {"rule":"ADT^A01", "name":"ADTA01"},
                {"rule":"ADT^A02", "name":"ADTA02"},
                {"rule":"ADT^A03", "name":"ADTA03"},
                {"rule":"ADT^A04", "name":"ADTA04"},
                {"rule":"ADT^A05", "name":"ADTA05"},
                {"rule":"ADT^A06", "name":"ADTA06"},
                {"rule":"ADT^A07", "name":"ADTA07"},
                {"rule":"ADT^A08", "name":"ADTA08"},
                {"rule":"ADT^A09", "name":"ADTA09"},
                {"rule":"ADT^A10", "name":"ADTA10"},
                {"rule":"ADT^A11", "name":"ADTA11"},
                {"rule":"ADT^A12", "name":"ADTA12"},
                {"rule":"ADT^A13", "name":"ADTA13"},
                {"rule":"ADT^A14", "name":"ADTA14"},
                {"rule":"ADT^A15", "name":"ADTA15"},
                {"rule":"ADT^A16", "name":"ADTA16"},
                {"rule":"ADT^A17", "name":"ADTA17"},
                {"rule":"ADT^A18", "name":"ADTA18"},
                {"rule":"ADT^A19", "name":"ADTA19"},
                {"rule":"ADT^A20", "name":"ADTA20"},
                {"rule":"ADT^A21", "name":"ADTA21"},
                {"rule":"ADT^A22", "name":"ADTA22"},
                {"rule":"ADT^A23", "name":"ADTA23"},
                {"rule":"ADT^A24", "name":"ADTA24"},
                {"rule":"ORM*"   , "name":"ORM"   },
                {"rule":"QRY^Q01", "name":"QRYQ01"},
                {"rule":"DSR*"   , "name":"DSR"   },
                {"rule":"QRY^Q03", "name":"QRYQ03"},
                {"rule":"MCF*"   , "name":"MCF"   },
                {"rule":"QRY^Q05", "name":"QRYQ05"},
                {"rule":"BAR^P01", "name":"BARP01"},
                {"rule":"BAR^P02", "name":"BARP02"},
                {"rule":"DFT^P03", "name":"DFTP03"},
                {"rule":"ORU^R01", "name":"ORUR01"},
                {"rule":"ORF*"   , "name":"ORF"   },
                {"rule":"NACK*"  , "name":"NACK"  }]
          }
;