BINARY=machine_id_check

SRC=\
MICmachineId.cpp\
main.cpp\

WIN_SRC=\
machine_id_check.rc\

MODULES=\
PRO\
IP\
RGN\
CMD\
FIL\
COL\

WIN_MODULES+=\
DBE\
SCK\
FIL\
REG\
SFI\

include ../makefiles/binary.makefile
