DIRS=\
COL\
TST\
CXML\
DOM\
XML\
EDI\
EXP\
LEG\
FIL\
CMD\
SFI\
NOX\
NTAB\
NOBT\
NODB\
NODBT\
NOB\
TSM\
TBM\
DB\
REG\
DBSQL\
SQL\
SQLTE\
NOD\
NODT\
THTM\
NTV\
FMT


include ../make/makefile.core
include ../OpenSSL/makefile.openssl

# DB includes dependencies on loading XML 
# DB depends on DBSQL and SQL and SQLTE
# EDI is a dependency of DB
