#ifndef __DBDVER_GIT_INFO_H__
#define __DBDVER_GIT_INFO_H__
//---------------------------------------------------------------------------
// Copyright (C) 1997-2021 iNTERFACEWARE Inc.  All Rights Reserved
//
// Module: DBDVERgitInfo
//
// Description:
//
// This header defines external const char* variables which are generated by the make process
//
// Author: Obner Usi
// Date:   Mon Mar 15 2021
//---------------------------------------------------------------------------

extern const char* DBDVER_BRANCH_NAME;
extern const char* DBDVER_TIME_STAMP;
extern const char* DBDVER_COMMIT_ID;
extern const char* DBDVER_COMMIT_MSG;

#endif // end of defensive include