#ifndef __SIG_SIGNALLER_H___
#define __SIG_SIGNALLER_H___
//---------------------------------------------------------------------------
// Copyright (C) 1997-2006 iNTERFACEWARE Inc.  All Rights Reserved
//
// Module: SIGsignaller (copied from COLsignal.h).
// Description: SIGsignaller is used to implement event handling. When declaring 
// SIGsignaller objects, follow the format SIGsignallerx, where x is the number of 
// parameters the function takes. The declaration would be as follows:
//
// class ExampleEvent
// {
//    void testInvoke(Example* pExample, int Param2);
//    SIGsignaller1 <Example*> event1;
//    SIGsignaller2 <Example*, int> event2;
// };
//
// Connecting a signal to a member function on some other instance is done by:
//
//  class MyReceivingClass : public SIGsignalReceiver
//  {
//    void myFunction(Example*,int);
//  }
//
// MyReceivingClass myInt;
// ExampleEvent iExampleEvent;
//
// //note that the explicit declaration of the member function pointer is important, some compilers
// //won't know how to compile unless the full declaration is provided
// iExampleEvent.event2.addReceiver(&MyReceivingClass::myFunction,myInt);
// 
// It is important that the receiving class inherit from SIGsignalReceiver, else a compile error will result.
// SIGsignalReceiver indicates that if the class is destroyed, any signallers sending to that instance 
// are automatically disconnected, avoiding access violations when the signal is invoked.
//
// SIGsignaller can also signal to plain functions without an instance:
//
// void myFunction(Example*,int){ //do something }
// iExampleEvent.event2.addReceiver(&myFunction);
//
// Invoke the signal by calling signal(), e.g:
//
// void ExampleEvent::void testInvoke(Example* pExample, int Param2);
// {
//    event2.signal(pExample,Param2);
// }
// 
// This will call all plain and member functions connected to event2.
// The order of invocation is undefined and should not be relied upon.
//
// The SIGsignaller objects can be used when one signal is connected to many 
// member functions or plain functions (slots).
//
// SIGsignaller was created to replace the need for inheritance with virtual 
// functions, which does not allow more than one object to override the 
// virtual function in the inheriting class. With SIGsignaller, one type can be
// instantiated many times, with each instance's event pointing to a
// different function that can be on any object.
//
// Author: Nasron Cheong
// Date:   Sept 2004
//
//---------------------------------------------------------------------------


/*
  NOTE
  Since this file represents an array of callback classes, one for each unique
  parameter count, that all have the same implementation the classes are 
  generated by macros.
  The implementation is in SIGsignallerM.h
  This file generates each SIGsignallerM template class.

*/

// Define this value to determine the max number of slot/signals sets
// to build. This linearly reduces the total number of included classes
// so per project, its advisable to keep this number as low as possible
// to increase compile time. Each set adds about 78kB to the precompiled
// header.
#ifndef SIG_SIGNALLER_PARAM_MAX
#define SIG_SIGNALLER_PARAM_MAX 3
#endif

#if SIG_SIGNALLER_PARAM_MAX >= 0
#include "SIGsignaller0.h"
#endif

#if SIG_SIGNALLER_PARAM_MAX >= 1
#include "SIGsignaller1.h"
#endif

#if SIG_SIGNALLER_PARAM_MAX >= 2
#include "SIGsignaller2.h"
#endif

#if SIG_SIGNALLER_PARAM_MAX >= 3
#include "SIGsignaller3.h"
#endif

#if SIG_SIGNALLER_PARAM_MAX >= 4
#include "SIGsignaller4.h"
#endif

#endif // end of defensive include
