TARGET=IguanaLicense

DIRS=\
DRX\
USR\
POP\
HASH\
MATCH\
PRM\
ROL\
CFG\
SDB\
WEB\
USG\
PASS\
CACHE\
GZIP\
WEBI\
SCKB\
SCKS\
PACK\
GUID\
SCK\
INFO\
ENV\
ENVC\
DIR\
PRO\
SFI\
RGN\
REG\
FIL\
CMD\
COL\
TXT\
ICONV\
REX\
PCRE\
GIT\
GITU\
GSV\
INI\
HTOOL\

include ../make/makefile.core
include ../libcurl/makefile.libcurl
