DIRS=\
GRID\
GRIDI\
GRIDS\
UNIT\
FIL\
SCK\
PRO\
CMD\
COL\
SCKS\
DIR\
TUN\
SFI\
IWEB\
POP\
CRT\
GUID\
CSV\
INFO\
ENV\
ENVC\
PRM\
ROL\
HASH\
CFG\
PASS\

include ../make/makefile.core
include ../OpenSSL/makefile.openssl
