#ifndef __TRN_EXTRACT_ERROR_STRING_H__
#define __TRN_EXTRACT_ERROR_STRING_H__
//---------------------------------------------------------------------------
// Copyright (C) 1997-2012 iNTERFACEWARE Inc.  All Rights Reserved
//
// Module: TRNextractErrorString
//
// Description:
//
// Helper to extract error string - it will try and convert non-strings into strings using the __tostring method
// via the print function.
//
// Author: Kevin Senn
// Date:   Friday, November 26th, 2010 @ 12:57:05 PM
//---------------------------------------------------------------------------

#include <COL/COLminimumInclude.h>
#include <COL/COLvar.h>

class TRNannotationState;
struct lua_State;

// If a function throws an error that is not string based, this function is 
// used to generate the string to be shown in the UI (generated by calling the
// error's __tostring metamethod).
void TRNextractErrorString( lua_State* L );

#endif // end of defensive include