DIRS=\
UNIT\
USR\
PRM\
ROL\
HASH\
MATCH\
SDB\
INFO\
ENV\
ENVC\
CDIR\
SCK\
FIL\
CMD\
POP\
PRO\
COL\
GUID\
SFI\
DIR\
CFG\
PASS\
TXT\
ICONV\
REX\
PCRE\
GIT\
GITU\
INI\
HTOOL\
GSV\

include ../make/makefile.core
include ../OpenSSL/makefile.openssl
