error_log /var/log/nginx/error.log;
http {

    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        server_name my2.interfaceware.com;
        return 301 https://my2.interfaceware.com$request_uri;
    }

    server {
        listen 443 ssl;
        listen [::]:443;

        ssl on;
        ssl_certificate #replace with ssl_certificate location
        ssl_certificate_key #replace with ssl_certificate_key location

        server_name my2.interfaceware.com;
        root /var/www/my.interfaceware.com;

        location / {
            if (-f $document_root/maintenance_on.html) {
                return 503;
            }
            proxy_pass https://localhost:2000/;
        }
        error_page 503 @maintenance;
        location @maintenance {
            if ($uri !~ ^/assets/) {
                rewrite ^(.*)$ /maintenance_on.html break;
            }
        }
    }
}
events {
    worker_connections 768;
}
