#ifndef __NOB_PARSE_H__
#define __NOB_PARSE_H__
//---------------------------------------------------------------------------
// Copyright (C) 1997-2010 iNTERFACEWARE Inc.  All Rights Reserved
//
// Module: NOBparse
//
// Description:
//
// NOBparse() will parse binary data generated by NOBserialize().  The
// result will be a NOD tree which represents a read-only copy of the
// tree which was serialized.
//
// Author: Kevin Senn
// Date:   Wednesday, November 3rd, 2010 @ 11:43:22 AM
//---------------------------------------------------------------------------

class NODplace;
class COLstring;

// Calling code should assume ownership of the pointer.
NODplace* NOBparse(COLstring& Source);

#endif // end of defensive include
