DIRS=\
RGN\
PRO\
REG\
XML\
FMT\
SFI\
TST\
FIL\
CMD\
PCRE\
LEG\
COL\
EXP\

# Windows Notes:
# Link dependencies: - RGNmachineIdWindows.obj : Iphlpapi.lib
# Must run test.exe with Admin privilege to avoid "Could not read/write registry entry. Please restart the application as a user with Administrator access to initialize the registry."

include ../make/makefile.core
include ../OpenSSL/makefile.openssl
