git mv BLUAexample/makefile.new BLUAexample/makefile
git mv CMDexample/makefile.new CMDexample/makefile
git mv COLexample/makefile.new COLexample/makefile
git mv CPPexample/makefile.new CPPexample/makefile
git mv CPUIDexample/makefile.new CPUIDexample/makefile
git mv DBDexample/makefile.new DBDexample/makefile
git mv DBexample/makefile.new DBexample/makefile
git mv DOMexample/makefile.new DOMexample/makefile
git mv FILexample/makefile.new FILexample/makefile
git mv FMTexample/makefile.new FMTexample/makefile
git mv GITexample/makefile.new GITexample/makefile
git mv GRIDIexample/makefile.new GRIDIexample/makefile
git mv GZIPexample/makefile.new GZIPexample/makefile
git mv HTTPexample/makefile.new HTTPexample/makefile
git mv IDBexample/makefile.new IDBexample/makefile
git mv INFOexample/makefile.new INFOexample/makefile
git mv IPAexample/makefile.new IPAexample/makefile
git mv IWEBexample/makefile.new IWEBexample/makefile
git mv Iguana/makefile.new Iguana/makefile
git mv LEGexample/makefile.new LEGexample/makefile
git mv LUAexample/makefile.new LUAexample/makefile
git mv MZIPexample/makefile.new MZIPexample/makefile
git mv NODexample/makefile.new NODexample/makefile
git mv NOTIexample/makefile.new NOTIexample/makefile
git mv NTBexample/makefile.new NTBexample/makefile
git mv QUEexample/makefile.new QUEexample/makefile
git mv REGexample/makefile.new REGexample/makefile
git mv REXexample/makefile.new REXexample/makefile
git mv RGNexample/makefile.new RGNexample/makefile
git mv SCKSexample/makefile.new SCKSexample/makefile
git mv SCKexample/makefile.new SCKexample/makefile
git mv SFIexample/makefile.new SFIexample/makefile
git mv SIGexample/makefile.new SIGexample/makefile
git mv SQLexample/makefile.new SQLexample/makefile
git mv TANexample/makefile.new TANexample/makefile
git mv TIMEexample/makefile.new TIMEexample/makefile
git mv TSMexample/makefile.new TSMexample/makefile
git mv TSTexample/makefile.new TSTexample/makefile
git mv TXTexample/makefile.new TXTexample/makefile
git mv UNITexample/makefile.new UNITexample/makefile
git mv USRexample/makefile.new USRexample/makefile
git mv WEBexample/makefile.new WEBexample/makefile
git mv XMLexample/makefile.new XMLexample/makefile
